# Generated by Django 3.1.3 on 2020-12-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_userprofile_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
