# Generated by Django 3.1.3 on 2020-12-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_auto_20201201_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('employee', 'employee'), ('customer', 'customer')], default='customer', max_length=250),
        ),
    ]
