# Generated by Django 3.1.3 on 2020-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_userprofile_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_date_time', models.DateTimeField(default='20:00')),
                ('total_price', models.IntegerField(default=0)),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('delivering', 'delivering'), ('delivered', 'delivered')], default='pending', max_length=250)),
                ('pizzas', models.CharField(default='Pepperoni', max_length=250)),
            ],
        ),
    ]
