# Generated by Django 3.1.3 on 2020-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0008_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_id',
            field=models.IntegerField(default='0'),
        ),
    ]
