# Generated by Django 3.1.3 on 2020-12-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0010_remove_pizza_pizza_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_id',
            field=models.IntegerField(default='0'),
        ),
    ]
