# Generated by Django 3.1.3 on 2020-12-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0016_order_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='pizza_app.Topping'),
        ),
    ]
