# Generated by Django 3.1.3 on 2020-12-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0017_auto_20201218_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
