# Generated by Django 3.1.3 on 2020-12-18 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0018_topping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
