# Generated by Django 3.1.1 on 2020-11-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20201101_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_rank',
            field=models.CharField(default='Basic', max_length=10),
        ),
    ]
