# Generated by Django 3.1.3 on 2020-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20201101_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_rank',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('Employe', 'Employe'), ('User', 'User')], default='User', max_length=250),
        ),
    ]
