# Generated by Django 3.1.3 on 2020-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20201125_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('employee', 'employee'), ('user', 'user')], default='user', max_length=250),
        ),
    ]
