# Generated by Django 3.1.3 on 2020-12-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20201127_0909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
